theme: jekyll-theme-minimal
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fstock.adobe.com%2Fsearch%3Fk%3Dcomputer%2Bcartoon&psig=AOvVaw0JRUVy_K7H6y8jh2VYQ661&ust=1717613957234000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPjN1N_QwoYDFQAAAAAdAAAAABAEtitle: Bioinformatics
