theme: jekyll-theme-minimal
logo: https://www.google.com/imgres?q=rat&imgurl=https%3A%2F%2Fi.natgeofe.com%2Fn%2F694d7d03-099a-4b1f-8e24-84618d22c40a%2FNationalGeographic_1099295_2x3.jpg&imgrefurl=https%3A%2F%2Fwww.nationalgeographic.com%2Fanimals%2Fmammals%2Ffacts%2Frats&docid=_Fbrl43D2SJCIM&tbnid=y19DfkRvDt_DkM&vet=12ahUKEwjmvI3bvMKGAxUtmO4BHbtcBnYQM3oECBMQAA..i&w=2049&h=3072&hcb=2&ved=2ahUKEwjmvI3bvMKGAxUtmO4BHbtcBnYQM3oECBMQAA
title: Bioinformatics
